HTML_CONTENT_MODEL = {

'%Script': { content: {  'cdata': 1} }, 
'%block': { content: {  'p': 1, 'h1': 1, 'h2': 1, 'h3': 1, 'h4': 1, 'h5': 1, 'h6': 1, 'ul': 1, 'ol': 1, 'dir': 1, 'menu': 1, 'pre': 1, 'dl': 1, 'div': 1, 'center': 1, 'noscript': 1, 'noframes': 1, 'blockquote': 1, 'form': 1, 'isindex': 1, 'hr': 1, 'table': 1, 'fieldset': 1, 'address': 1} }, 
'%flow': { content: {  'p': 1, 'h1': 1, 'h2': 1, 'h3': 1, 'h4': 1, 'h5': 1, 'h6': 1, 'ul': 1, 'ol': 1, 'dir': 1, 'menu': 1, 'pre': 1, 'dl': 1, 'div': 1, 'center': 1, 'noscript': 1, 'noframes': 1, 'blockquote': 1, 'form': 1, 'isindex': 1, 'hr': 1, 'table': 1, 'fieldset': 1, 'address': 1, '#pcdata': 1, 'tt': 1, 'i': 1, 'b': 1, 'u': 1, 's': 1, 'strike': 1, 'big': 1, 'small': 1, 'em': 1, 'strong': 1, 'dfn': 1, 'code': 1, 'samp': 1, 'kbd': 1, 'var': 1, 'cite': 1, 'abbr': 1, 'acronym': 1, 'a': 1, 'img': 1, 'applet': 1, 'object': 1, 'font': 1, 'basefont': 1, 'br': 1, 'script': 1, 'map': 1, 'q': 1, 'sub': 1, 'sup': 1, 'span': 1, 'bdo': 1, 'iframe': 1, 'input': 1, 'select': 1, 'textarea': 1, 'label': 1, 'button': 1} }, 
'%formctrl': { content: {  'input': 1, 'select': 1, 'textarea': 1, 'label': 1, 'button': 1} }, 
'%head.content': { content: {  'title': 1, '&': 1, 'isindex': 1, '&': 1, 'base': 1} }, 
'%head.misc': { content: {  'script': 1, 'style': 1, 'meta': 1, 'link': 1, 'object': 1} }, 
'%html.content': { content: {  'head': 1, 'body': 1} }, 
'%inline': { content: {  '#pcdata': 1, 'tt': 1, 'i': 1, 'b': 1, 'u': 1, 's': 1, 'strike': 1, 'big': 1, 'small': 1, 'em': 1, 'strong': 1, 'dfn': 1, 'code': 1, 'samp': 1, 'kbd': 1, 'var': 1, 'cite': 1, 'abbr': 1, 'acronym': 1, 'a': 1, 'img': 1, 'applet': 1, 'object': 1, 'font': 1, 'basefont': 1, 'br': 1, 'script': 1, 'map': 1, 'q': 1, 'sub': 1, 'sup': 1, 'span': 1, 'bdo': 1, 'iframe': 1, 'input': 1, 'select': 1, 'textarea': 1, 'label': 1, 'button': 1} }, 
'%noframes.content': { content: {  'p': 1, 'h1': 1, 'h2': 1, 'h3': 1, 'h4': 1, 'h5': 1, 'h6': 1, 'ul': 1, 'ol': 1, 'dir': 1, 'menu': 1, 'pre': 1, 'dl': 1, 'div': 1, 'center': 1, 'noscript': 1, 'noframes': 1, 'blockquote': 1, 'form': 1, 'isindex': 1, 'hr': 1, 'table': 1, 'fieldset': 1, 'address': 1, '#pcdata': 1, 'tt': 1, 'i': 1, 'b': 1, 'u': 1, 's': 1, 'strike': 1, 'big': 1, 'small': 1, 'em': 1, 'strong': 1, 'dfn': 1, 'code': 1, 'samp': 1, 'kbd': 1, 'var': 1, 'cite': 1, 'abbr': 1, 'acronym': 1, 'a': 1, 'img': 1, 'applet': 1, 'object': 1, 'font': 1, 'basefont': 1, 'br': 1, 'script': 1, 'map': 1, 'q': 1, 'sub': 1, 'sup': 1, 'span': 1, 'bdo': 1, 'iframe': 1, 'input': 1, 'select': 1, 'textarea': 1, 'label': 1, 'button': 1} }, 
'%pre.exclusion': { content: {  'img': 1, 'object': 1, 'applet': 1, 'big': 1, 'small': 1, 'sub': 1, 'sup': 1, 'font': 1, 'basefont': 1} },
'': { model: 'unknown', content: {  '%inline': 1} },
'%fontstyle;': { content: {  '%inline': 1} },
'%heading;': { content: {  '%inline': 1} },
'%phrase;': { content: {  '%inline': 1} },
'a': { model: 'inline', content: {  '%inline': 1, 'a': 1} },
'abbr': { model: 'inline', content: {  '%inline': 1} },
'acronym': { model: 'inline', content: {  '%inline': 1} },
'address': { model: 'inline', content: {  '%inline': 1, 'p': 1} },
'applet': { model: 'unknown', content: {  'param': 1, '%flow': 1} },
'area': { model: 'unknown', content: { } },
'b': { model: 'inline', content: {  '%inline': 1} },
'base': { model: 'unknown', content: { } },
'basefont': { model: 'unknown', content: { } },
'bdo': { model: 'unknown', content: {  '%inline': 1} },
'big': { model: 'inline', content: {  '%inline': 1} },
'blockquote': { model: 'block', content: {  '%flow': 1} },
'body': { model: 'block', content: {  '%flow': 1, 'ins': 1, 'del': 1} },
'br': { model: 'block', content: { } },
'button': { model: 'block', content: {  '%flow': 1, 'a': 1, '%formctrl': 1, 'form': 1, 'isindex': 1, 'fieldset': 1, 'iframe': 1} },
'caption': { model: 'block', content: {  '%inline': 1} },
'center': { model: 'unknown', content: {  '%flow': 1} },
'cite': { model: 'inline', content: {  '%inline': 1} },
'code': { model: 'inline', content: {  '%inline': 1} },
'col': { model: 'block', content: { } },
'colgroup': { model: 'block', content: {  'col': 1} },
'dd': { model: 'block', content: {  '%flow': 1} },
'del': { model: 'inline', content: {  '%flow': 1} },
'dfn': { model: 'inline', content: {  '%inline': 1} },
'dir': { model: 'block', content: {  'li': 1, '%block': 1} },
'div': { model: 'block', content: {  '%flow': 1} },
'dl': { model: 'block', content: {  'dt': 1, 'dd': 1} },
'dt': { model: 'block', content: {  '%inline': 1} },
'em': { model: 'inline', content: {  '%inline': 1} },
'fieldset': { model: 'block', content: {  '#pcdata': 1, 'legend': 1, '%flow': 1} },
'font': { model: 'inline', content: {  '%inline': 1} },
'form': { model: 'block', content: {  '%flow': 1, 'form': 1} },
'frame': { model: 'unknown', content: { } },
'frameset': { model: 'unknown', content: {  'frameset': 1, 'frame': 1, '&': 1, 'noframes': 1} },
'h1': { model: 'block', content: {  '%inline': 1} },
'h2': { model: 'block', content: {  '%inline': 1} },
'h3': { model: 'block', content: {  '%inline': 1} },
'h4': { model: 'block', content: {  '%inline': 1} },
'h5': { model: 'block', content: {  '%inline': 1} },
'h6': { model: 'block', content: {  '%inline': 1} },
'head': { model: 'unknown', content: {  '%head.content': 1, '%head.misc': 1} },
'hr': { model: 'block', content: { } },
'html': { model: 'block', content: {  '%html.content': 1} },
'i': { model: 'inline', content: {  '%inline': 1} },
'iframe': { model: 'block', content: {  '%flow': 1} },
'img': { model: 'inline', content: { } },
'input': { model: 'block', content: { } },
'ins': { model: 'inline', content: {  '%flow': 1} },
'isindex': { model: 'block', content: { } },
'kbd': { model: 'inline', content: {  '%inline': 1} },
'label': { model: 'block', content: {  '%inline': 1, 'label': 1} },
'legend': { model: 'block', content: {  '%inline': 1} },
'li': { model: 'block', content: {  '%flow': 1} },
'link': { model: 'unknown', content: { } },
'map': { model: 'unknown', content: {  '%block': 1, 'area': 1} },
'menu': { model: 'block', content: {  'li': 1, '%block': 1} },
'meta': { model: 'unknown', content: { } },
'noframes': { model: 'unknown', content: {  '%noframes.content': 1} },
'noscript': { model: 'unknown', content: {  '%flow': 1} },
'object': { model: 'block', content: {  'param': 1, '%flow': 1} },
'ol': { model: 'block', content: {  'li': 1} },
'optgroup': { model: 'block', content: {  'option': 1} },
'option': { model: 'block', content: {  '#pcdata': 1} },
'p': { model: 'block', content: {  '%inline': 1} },
'param': { model: 'unknown', content: { } },
'pre': { model: 'block', content: {  '%inline': 1, '%pre.exclusion': 1} },
'q': { model: 'inline', content: {  '%inline': 1} },
's': { model: 'inline', content: {  '%inline': 1} },
'samp': { model: 'inline', content: {  '%inline': 1} },
'script': { model: 'none', content: {  '%script': 1} },
'select': { model: 'block', content: {  'optgroup': 1, 'option': 1} },
'small': { model: 'inline', content: {  '%inline': 1} },
'span': { model: 'inline', content: {  '%inline': 1} },
'strike': { model: 'inline', content: {  '%inline': 1} },
'strong': { model: 'inline', content: {  '%inline': 1} },
'style': { model: 'none', content: {  '%stylesheet': 1} },
'sub': { model: 'inline', content: {  '%inline': 1} },
'sup': { model: 'inline', content: {  '%inline': 1} },
'table': { model: 'block', content: {  'caption': 1, 'col': 1, 'colgroup': 1, 'thead': 1, 'tfoot': 1, 'tbody': 1} },
'tbody': { model: 'block', content: {  'tr': 1} },
'td': { model: 'block', content: {  '%flow': 1} },
'textarea': { model: 'block', content: {  '#pcdata': 1} },
'tfoot': { model: 'block', content: {  'tr': 1} },
'th': { model: 'block', content: {  '%flow': 1} },
'thead': { model: 'block', content: {  'tr': 1} },
'title': { model: 'unknown', content: {  '#pcdata': 1, '%head.misc': 1} },
'tr': { model: 'block', content: {  'th': 1, 'td': 1} },
'tt': { model: 'inline', content: {  '%inline': 1} },
'u': { model: 'inline', content: {  '%inline': 1} },
'ul': { model: 'block', content: {  'li': 1} },
'var': { model: 'unknown', content: {  '%inline': 1} }}
